### ISSUE TITLE
FIX: Mistake on textParams -> umpossible to change FontSize on bar

### ISSUE THREAD

**Issue by Wiew1** [lemelech/matlab-barvalues#2]
Hi, i found a mistake in your code and i fix it. 

On line 59 you have            t = [t; {barvalues(b,precision}]; % Return array of text objects
but in case if you wanna to show text in bar, it is impossible to change the text params. It was chaused by recursivelly calling the function. Calling barvalues function from main function was ok, but your function calling this function recursivelly and on line 59 you clear variable textParams. 

New version of line 59:
 t = [t; {barvalues(b,precision,**textParams**}]; % Return array of text objects

Calling the function:
h = figure;
bar(Y)
barvalues(h,'% .0f',{'FontSize', 50,'FontWeight', 'bold'})
[barvalues.zip](https://github.com/lemelech/matlab-barvalues/files/7737836/barvalues.zip)

Have a nice day!
Wiew

**Comment by lemelech** [comment]
thx, i'll test & apply your fix.
Nice catch!
